import { observer } from "mobx-react-lite";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useContext, useEffect } from "react";
import { Listitem, Navbar, Navbarbot } from "../components";
import { Store } from "../stores/store";

const Home: NextPage = observer(() => {
  const { queryStore } = useContext(Store);

  const router = useRouter();
  const { query } = router.query;
  const getGames = async () => {
    if (query == undefined) {
      return await queryStore.getGames();
    } else if (query == "30days") {
      return await queryStore.getGamesLast30();
    } else if (query == "lastWeek") {
      return await queryStore.getGamesLastWeek();
    } else if (query == "nextWeek") {
      return await queryStore.getGamesNextWeek();
    }
  };

  useEffect(() => {
    getGames();
  }, [query]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Navbarbot />
      <div className="flex flex-col gap-3">
        {queryStore.games &&
          queryStore.games.map((game) => {
            return (
              <Listitem
                key={game.id}
                gameid={game.id}
                background_image={game.background_image}
                release_date={game.released}
                stars={game.rating}
                parent_platforms={game.parent_platforms}
                title={game.name}
              />
            );
          })}
      </div>

      <main></main>

      <footer></footer>
    </div>
  );
});

export default Home;
