import { observer } from "mobx-react-lite";
import type { NextPage } from "next";
import Head from "next/head";
import { useContext, useEffect } from "react";
import { Listitem, Navbar, Navbarbot } from "../components";
import { Store } from "../stores/store";

const Home: NextPage = observer(() => {
  const { queryStore } = useContext(Store);

  const getGames = async () => {
    await queryStore.getGames();
  };

  useEffect(() => {
    getGames();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Navbarbot />
      <div className="flex flex-col gap-3">
        {queryStore.games &&
          queryStore.games.map((game) => {
            return (
              <Listitem
                key={game.id}
                background_image={game.background_image}
                release_date={game.released}
                stars={game.rating}
                parent_platforms={game.parent_platforms}
                title={game.name}
              />
            );
          })}
      </div>

      <main></main>

      <footer></footer>
    </div>
  );
});

export default Home;
