import { observer } from "mobx-react-lite";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useContext, useEffect } from "react";
import { Oval } from "react-loader-spinner";
import { Listitem, Navbar, Navbarbot } from "../../components";
import { Store } from "../../stores/store";
import InfiniteScroll from "react-infinite-scroll-component";
import sanitizeHtml from "sanitize-html";

const GenreId = observer(() => {
  const router = useRouter();
  const { id } = router.query;

  const { queryStore } = useContext(Store);

  const getGames = async () => {
    if (typeof id === "string") {
      await queryStore.getGenreById(id);
      await queryStore.getGamesByGenre(id);
    }
  };
  const expandGames = async () => {
    await queryStore.expandGames();
  };

  const { genre, games } = queryStore;

  let description = "";
  if (genre?.description != undefined) {
    description = sanitizeHtml(genre?.description, { allowedTags: [] });
  }

  useEffect(() => {
    getGames();
  }, [id]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Navbarbot />
      {queryStore.isLoading ? (
        <div className="w-full h-screen flex justify-center items-center">
          <Oval color="white" />
        </div>
      ) : (
        games &&
        queryStore.count && (
          <InfiniteScroll
            dataLength={games.length}
            next={expandGames}
            hasMore={games.length < queryStore.count}
            loader={<h4>Loading...</h4>}
          >
            <main className="flex flex-col lg:gap-3">
              <div className="flex flex-row mb-7 ">
                <div className="flex flex-col 2xl:flex-row gap-4">
                  <h4 className="text-5xl lg:text-9xl">{genre?.name}</h4>
                  <p className="text-xs lg:text-sm overflow-x-scroll scrollbar-hide">
                    {description}
                  </p>
                </div>
              </div>
              {games && (
                <div className="flex flex-col gap-3">
                  {games.map((game) => {
                    return (
                      <Listitem
                        key={game.id}
                        background_image={game.background_image}
                        gameid={game.id}
                        parent_platforms={game.parent_platforms}
                        release_date={game.released}
                        stars={game.rating}
                        title={game.name}
                      />
                    );
                  })}
                </div>
              )}
            </main>
          </InfiniteScroll>
        )
      )}
      <footer></footer>
    </div>
  );
});

export default GenreId;
