import { observer } from "mobx-react-lite";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useContext, useEffect } from "react";
import InfiniteScroll from "react-infinite-scroll-component";
import { Oval } from "react-loader-spinner";
import { Listitem, Navbar, Navbarbot } from "../../components";
import { Store } from "../../stores/store";
import sanitizeHtml from "sanitize-html";
import Layout from "../layout";

const PublisherId = observer(() => {
  const router = useRouter();
  const { id } = router.query;

  const { queryStore } = useContext(Store);

  const getGames = async () => {
    if (typeof id === "string") {
      await queryStore.getPublisherById(id);
      await queryStore.getGamesByPublisher(id);
    }
  };
  const expandGames = async () => {
    await queryStore.expandGames();
  };

  const { publisher, games } = queryStore;

  let description = "";
  if (publisher?.description != undefined) {
    description = sanitizeHtml(publisher?.description, { allowedTags: [] });
  }

  useEffect(() => {
    getGames();
  }, [id]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {queryStore.isLoading ? (
          <div className="w-full h-screen flex justify-center items-center">
            <Oval color="white" />
          </div>
        ) : (
          games &&
          queryStore.count && (
            <InfiniteScroll
              dataLength={games.length}
              next={expandGames}
              hasMore={games.length < queryStore.count}
              loader={<h4>Loading...</h4>}
            >
              <main className="flex flex-col gap-3">
                <div className="flex flex-row">
                  <div className="flex flex-col 2xl:flex-row gap-4">
                    <h4 className="text-4xl lg:text-8xl">{publisher?.name}</h4>
                    <p className="text-xs lg:text-sm">{description}</p>
                  </div>
                </div>
                {games &&
                  games.map((game) => {
                    return (
                      <Listitem
                        key={game.id}
                        background_image={game.background_image}
                        gameid={game.id}
                        parent_platforms={game.parent_platforms}
                        release_date={game.released}
                        stars={game.rating}
                        title={game.name}
                      />
                    );
                  })}
              </main>
            </InfiniteScroll>
          )
        )}
      </Layout>
    </div>
  );
});

export default PublisherId;
